FROM php:7.4-apache
RUN docker-php-ext-install mysqli
COPY src/ /var/www/html
CMD sed -i "s/80/$PORT/g" /etc/apache2/sites-enabled/000-default.conf /etc/apache2/ports.conf && docker-php-entrypoint apache2-foreground
